"""Settings for the MOEX margined-option examples.

**The option prices are synthetic.** The underlying is not: SBER daily bars come from your gRPC
source. The chain on top of them is generated by a model, because OPRA quotes are closed by the
token's entitlements and the feed lists no expired MOEX series. No number produced here describes
a return -- see :data:`ziplime.data.data_sources.options.synthetic.SYNTHETIC_DATA_WARNING`.

What *is* real here, and measured against the feed:

* the underlying of SBER options is the **SBER@MISX share**, not the future (the feed's
  ``underlying_asset`` field says so);
* expiries fall on Wednesdays: **monthly** on the third Wednesday, weeklies in between;
* the contracts are EUROPEAN, settle CASH, and report ``contract_size = 1``;
* they are named ``SR310CI6`` and the like;
* and, above all, they are **margined**: no premium changes hands at the trade.
"""
import datetime
from pathlib import Path

ASSET_DB_PATH = str(Path(Path(__file__).parent.parent.parent, "assets.sqlite").absolute())

#: The underlying. SBER is the most liquid option market on MOEX.
UNDERLYING = ("SBER", "MISX")
UNDERLYING_ROOT = "SR"
TRADING_CALENDAR = "XMOS"

#: Daily bars rather than intraday, and that is a deliberate choice.
#:
#: A MOEX option trades rarely: on a real contract I measured 23-54 minute bars in a session
#: instead of five hundred. An intraday strategy on a book like that is an exercise in slippage
#: rather than in logic. On top of that FORTS runs until 23:50 while the XMOS calendar in
#: exchange_calendars ends the session at 18:45, so an intraday run would quietly lose the evening
#: session.
EMISSION_RATE = datetime.timedelta(days=1)

#: The window. Expiries are weekly, so a quarter holds about thirteen of them -- enough to see
#: several cycles rather than one.
SESSIONS_BACK = 120

#: The examples trade the **monthly** series -- the third Wednesday of the month.
#:
#: Not the weeklies, and that is forced. A MOEX option code carries the month but not the day:
#: measured, 2026-09-16 is ``SR300CI6``, 2026-09-23 is ``SR300CI6D``, and 2026-09-30 is already
#: ``SR300CJ6A``, with October's month letter. The rule relating a weekly's date to its letters
#: does not follow from three observations, and inventing one collapses three series into one.
#: Monthlies are named unambiguously, and the round trip closes on them.
#:
#: In practice this costs nothing: the monthly series are the most liquid, and a 120-session
#: window holds about six of them -- enough cycles to see behaviour rather than one accident.
EXPIRY_WEEKDAY = 2

#: How many sessions a series lives before its expiry. A monthly trades well ahead of expiry;
#: twenty sessions is about a month and exactly one cycle. For 0DTE this would be 0.
LIFE_SESSIONS = 20

STARTING_CASH = 1_000_000.0

#: The strike grid. SBER around 283 roubles lists five-rouble strikes -- taken from a live chain.
NEAR_STEP, NEAR_REACH = 5.0, 25.0
FAR_STEP, FAR_REACH = 10.0, 60.0

#: Initial margin as a fraction of a position's notional. MOEX computes margin with its own model;
#: a flat rate is used here because the point of the examples is to show that margin is consumed
#: and does limit size, not to reproduce the exchange's methodology.
INITIAL_MARGIN_RATE = 0.15
MAINTENANCE_MARGIN_RATE = 0.12

#: Volume in one bar at the at-the-money strike. The bars here are daily, so the figure is daily
#: too: a minute figure (in the hundreds) would cut every fill down to a few contracts, and the
#: strategy's sizing would stop mattering -- the volume cap would decide everything.
ATM_DAILY_VOLUME = 3_000.0
